In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('dataset.csv')

In [9]:
df.head()

,order_id,customer_id,age,gender,country,city,registration_date,product_id,product_name,brand,category,condition,price,order_date,quantity,total_price,age_group,product_type
0,1,443,59.0,Female,Latvia,Daugavpils,2025-01-06,179,Levi's Jacket 179,L e v i ' s,Jacket,Like New,49.57,2024-12-14,1,49.57,Senior,jacket
1,2,1991,61.0,Female,Latvia,Daugavpils,2024-02-03,296,Nike T-Shirt 296,N i k e,T-Shirt,Fair,43.11,2025-06-16,1,43.11,Senior,t-shirt
2,3,1667,37.0,Male,Poland,Krakow,2024-04-07,187,Nike Jeans 187,N i k e,Jeans,New,143.69,2025-04-07,1,143.69,Adult,jeans
3,4,1837,49.0,Female,Poland,Krakow,2024-06-11,158,Nike T-Shirt 158,N i k e,T-Shirt,New,124.47,2024-10-07,3,373.41,Middle-aged,t-shirt
4,5,1433,36.0,Male,Estonia,Tartu,2025-12-02,256,Nike Jeans 256,N i k e,Jeans,Good,84.33,2025-09-11,3,252.99,Adult,jeans

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           10000 non-null  int64
 1   customer_id        10000 non-null  int64
 2   age                10000 non-null  float64
 3   gender             10000 non-null  object
 4   country            10000 non-null  object
 5   city               10000 non-null  object
 6   registration_date  10000 non-null  object
 7   product_id         10000 non-null  int64
 8   product_name       10000 non-null  object
 9   brand              10000 non-null  object
 10  category           10000 non-null  object
 11  condition          10000 non-null  object
 12  price              10000 non-null  float64
 13  order_date         10000 non-null  object
 14  quantity           10000 non-null  int64
 15  total_price        10000 non-null  float64
 16  age_group          10000 non-null  object
 17  product_type       10000 non-null  object
dtypes: float64(3), int64(4), object(11)
memory usage: 1.4+ MB

In [11]:
df.describe()

,order_id,customer_id,age,product_id,price,quantity,total_price
count,10000.00000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1003.15720,41.710200,151.601500,71.408035,1.980000,142.487415
std,2886.89568,578.43712,13.982245,87.063627,43.383931,0.840161,110.132316
min,1.00000,1.00000,18.000000,1.000000,5.180000,-1.000000,5.180000
25%,2500.75000,504.75000,29.000000,77.000000,32.220000,1.000000,54.820000
50%,5000.50000,993.00000,42.000000,152.000000,64.310000,2.000000,113.310000
75%,7500.25000,1510.25000,54.000000,226.000000,107.860000,3.000000,209.340000
max,10000.00000,2000.00000,65.000000,300.000000,149.480000,3.000000,448.440000

In [12]:
df.isnull().sum()

order_id             0
customer_id          0
age                  0
gender               0
country              0
city                 0
registration_date    0
product_id           0
product_name         0
brand                0
category             0
condition            0
price                0
order_date           0
quantity             0
total_price          0
age_group            0
product_type         0
dtype: int64

In [13]:
df["Price"] = df.groupby('Category')["Price"].transform(lambda x: x.fillna(x.median()))
df["Age"] = df.groupby('Category')["Age"].transform(lambda x: x.fillna(x.median()))

KeyError: 'Category'

In [14]:
df.isnull().sum()

order_id             0
customer_id          0
age                  0
gender               0
country              0
city                 0
registration_date    0
product_id           0
product_name         0
brand                0
category             0
condition            0
price                0
order_date           0
quantity             0
total_price          0
age_group            0
product_type         0
dtype: int64

In [15]:
df["Product Name"].unique()

KeyError: 'Product Name'

In [16]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [17]:
df.columns

Index(['order_id', 'customer_id', 'age', 'gender', 'country', 'city',
       'registration_date', 'product_id', 'product_name', 'brand', 'category',
       'condition', 'price', 'order_date', 'quantity', 'total_price',
       'age_group', 'product_type'],
      dtype='object')

In [18]:
#create a column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels=labels)

In [19]:
df[['age','age_group']].head(10)

    age    age_group
0  59.0       Senior
1  61.0       Senior
2  37.0        Adult
3  49.0  Middle-aged
4  36.0        Adult
5  44.0  Middle-aged
6  23.0  Young Adult
7  39.0        Adult
8  41.0        Adult
9  32.0        Adult

In [21]:
df["brand"] = df["product_name"].apply(
    lambda x: " ".join(str(x).split()[0])
)

In [28]:
df["category"] = df["category"].str.strip().str.lower()

df["category"] = df["category"].replace({
    "shoe": "shoes",
    "shoes": "shoes",
    "shoees": "shoes",
    "tshirt": "t-shirt"
})

In [29]:
df["product_type"].value_counts()

product_type
jeans      1929
shoes      1712
jacket     1682
t-shirt    1651
hoodie     1525
dress      1501
Name: count, dtype: int64

In [30]:
df.head(5)

,order_id,customer_id,age,gender,country,city,registration_date,product_id,product_name,brand,category,condition,price,order_date,quantity,total_price,age_group,product_type
0,1,443,59.0,Female,Latvia,Daugavpils,2025-01-06,179,Levi's Jacket 179,L e v i ' s,jacket,Like New,49.57,2024-12-14,1,49.57,Senior,jacket
1,2,1991,61.0,Female,Latvia,Daugavpils,2024-02-03,296,Nike T-Shirt 296,N i k e,t-shirt,Fair,43.11,2025-06-16,1,43.11,Senior,t-shirt
2,3,1667,37.0,Male,Poland,Krakow,2024-04-07,187,Nike Jeans 187,N i k e,jeans,New,143.69,2025-04-07,1,143.69,Adult,jeans
3,4,1837,49.0,Female,Poland,Krakow,2024-06-11,158,Nike T-Shirt 158,N i k e,t-shirt,New,124.47,2024-10-07,3,373.41,Middle-aged,t-shirt
4,5,1433,36.0,Male,Estonia,Tartu,2025-12-02,256,Nike Jeans 256,N i k e,jeans,Good,84.33,2025-09-11,3,252.99,Adult,jeans

In [31]:
df.to_csv("dataset.csv",index=False)