In [21]:
import pandas as pd
from sqlalchemy import create_engine

In [22]:
df = pd.read_csv('dataset.csv')

In [23]:
df.head()

,Order ID,Customer ID,Age,Gender,Country,City,Registration Date,Product ID,Product Name,Brand,Category,Condition,Price,Order Date,Quantity,Total Price
0,1,443,59.0,Female,Latvia,Daugavpils,2025-01-06,179,Levi's Jacket 179,Levi's,Jacket,Like New,49.57,2024-12-14,1,49.57
1,2,1991,61.0,Female,Latvia,Daugavpils,2024-02-03,296,Nike T-Shirt 296,Nike,T-Shirt,Fair,43.11,2025-06-16,1,43.11
2,3,1667,37.0,Male,Poland,Krakow,2024-04-07,187,Nike Jeans 187,Nike,Jeans,New,143.69,2025-04-07,1,143.69
3,4,1837,49.0,Female,Poland,Krakow,2024-06-11,158,Nike T-Shirt 158,Nike,T-Shirt,New,124.47,2024-10-07,3,373.41
4,5,1433,36.0,Male,Estonia,Tartu,2025-12-02,256,Nike Jeans 256,Nike,Jeans,Good,84.33,2025-09-11,3,252.99

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           10000 non-null  int64
 1   Customer ID        10000 non-null  int64
 2   Age                9900 non-null   float64
 3   Gender             10000 non-null  object
 4   Country            10000 non-null  object
 5   City               10000 non-null  object
 6   Registration Date  10000 non-null  object
 7   Product ID         10000 non-null  int64
 8   Product Name       10000 non-null  object
 9   Brand              10000 non-null  object
 10  Category           10000 non-null  object
 11  Condition          10000 non-null  object
 12  Price              9900 non-null   float64
 13  Order Date         10000 non-null  object
 14  Quantity           10000 non-null  int64
 15  Total Price        10000 non-null  float64
dtypes: float64(3), int64(4), object(9)
memory usage: 1.2+ MB

In [25]:
df.describe()

,Order ID,Customer ID,Age,Product ID,Price,Quantity,Total Price
count,10000.00000,10000.00000,9900.000000,10000.000000,9900.000000,10000.000000,10000.000000
mean,5000.50000,1003.15720,41.707273,151.601500,71.452253,1.980000,142.487415
std,2886.89568,578.43712,14.052661,87.063627,43.586144,0.840161,110.132316
min,1.00000,1.00000,18.000000,1.000000,5.180000,-1.000000,5.180000
25%,2500.75000,504.75000,29.000000,77.000000,31.350000,1.000000,54.820000
50%,5000.50000,993.00000,42.000000,152.000000,64.310000,2.000000,113.310000
75%,7500.25000,1510.25000,54.000000,226.000000,108.180000,3.000000,209.340000
max,10000.00000,2000.00000,65.000000,300.000000,149.480000,3.000000,448.440000

In [26]:
df.isnull().sum()

Order ID               0
Customer ID            0
Age                  100
Gender                 0
Country                0
City                   0
Registration Date      0
Product ID             0
Product Name           0
Brand                  0
Category               0
Condition              0
Price                100
Order Date             0
Quantity               0
Total Price            0
dtype: int64

In [27]:
df["Price"] = df.groupby('Category')["Price"].transform(lambda x: x.fillna(x.median()))
df["Age"] = df.groupby('Category')["Age"].transform(lambda x: x.fillna(x.median()))

In [28]:
df.isnull().sum()

Order ID             0
Customer ID          0
Age                  0
Gender               0
Country              0
City                 0
Registration Date    0
Product ID           0
Product Name         0
Brand                0
Category             0
Condition            0
Price                0
Order Date           0
Quantity             0
Total Price          0
dtype: int64

In [29]:
df["Product Name"].unique()

array(["Levi's Jacket 179", 'Nike T-Shirt 296', 'Nike Jeans 187',
       'Nike T-Shirt 158', 'Nike Jeans 256', 'Uniqlo Hoodie 211',
       'Adidas T-Shirt 278', "Levi's Jeans 172", 'Puma Dress 220',
       'Zara Dress 84', 'Nike Jeans 146', 'Uniqlo Jacket 224',
       'Puma Shoes 51', 'H&M T-Shirt 9', "Levi's T-Shirt 255",
       'Nike Hoodie 279', 'Zara Jeans 258', 'Adidas Dress 149',
       'Nike Shoes 233', 'Puma Dress 101', 'Nike Hoodie 238',
       'Puma Jeans 203', 'Uniqlo Shoes 115', 'Adidas Jacket 136',
       'Adidas Dress 124', 'Uniqlo Jeans 8', 'Adidas T-Shirt 192',
       'H&M Hoodie 202', 'Adidas Jacket 66', 'Nike Shoes 89',
       'Nike Dress 82', 'Adidas T-Shirt 65', 'Nike Shoes 134',
       'H&M Shoes 166', 'Puma Hoodie 14', 'Adidas T-Shirt 79',
       'Nike Jeans 13', 'Adidas Shoes 184', 'H&M Jeans 114',
       'H&M Dress 126', 'Adidas Jacket 43', 'Puma Shoes 297',
       "Levi's T-Shirt 63", 'H&M Jeans 135', "Levi's Hoodie 254",
       'Uniqlo Dress 52', 'Puma Shoes 38', 'Uniqlo Dress 108',
       'Puma Jacket 161', 'Uniqlo Shoes 83', "Levi's Jeans 92",
       'Puma Jacket 17', 'Puma Shoes 248', 'Puma Dress 3',
       'Zara Jeans 131', 'Uniqlo T-Shirt 16', 'Uniqlo Dress 263',
       'Puma Jeans 168', 'H&M Hoodie 103', 'Puma Jeans 283',
       'Uniqlo Jeans 205', 'Adidas Jacket 102', 'Nike Hoodie 160',
       'Adidas Hoodie 250', "Levi's Shoes 140", 'H&M Jacket 197',
       'Puma Dress 181', "Levi's Dress 33", 'Nike Shoes 18',
       'Zara Jeans 210', 'H&M T-Shirt 272', 'Uniqlo Jacket 59',
       "Levi's Dress 96", 'Adidas Hoodie 111', 'Puma T-Shirt 75',
       'Puma Jacket 164', 'Adidas Jeans 169', 'Puma T-Shirt 165',
       'Nike Hoodie 198', 'H&M Shoes 270', 'H&M Jacket 143',
       'Adidas Dress 39', 'Adidas Hoodie 223', 'Uniqlo Hoodie 24',
       'Puma T-Shirt 64', 'H&M Jeans 295', "Levi's T-Shirt 68",
       'H&M Jacket 274', 'Nike T-Shirt 213', 'Adidas Dress 163',
       'Puma Jacket 285', 'Puma Shoes 25', 'H&M T-Shirt 15',
       'Puma Jeans 6', 'Puma Jacket 98', 'H&M Jeans 276',
       'Uniqlo Hoodie 27', 'Uniqlo T-Shirt 195', 'Adidas Shoes 71',
       'Adidas Jacket 300', 'Uniqlo Hoodie 144', 'Adidas Dress 48',
       'Nike Shoes 125', 'Nike Shoes 106', 'H&M T-Shirt 271',
       "Levi's Dress 67", 'Zara T-Shirt 232', 'Adidas Shoes 217',
       'Adidas T-Shirt 237', 'Uniqlo T-Shirt 282', 'Puma Shoes 109',
       'Zara Jacket 221', 'H&M Jeans 226', "Levi's Hoodie 26",
       'Adidas Dress 207', 'Adidas Shoes 222', 'Nike Shoes 128',
       'Adidas T-Shirt 28', 'Zara Dress 123', "Levi's Shoes 142",
       'Uniqlo Shoes 208', 'Uniqlo Dress 113', 'Uniqlo Jacket 105',
       'Puma Hoodie 148', 'Zara Dress 95', 'Uniqlo Jeans 245',
       'H&M Jeans 36', 'Uniqlo Dress 234', 'Puma T-Shirt 243',
       'H&M Jacket 91', 'Zara Jeans 5', 'Zara Jacket 127',
       'Adidas Jacket 117', "Levi's Jeans 76", 'H&M Jeans 180',
       'Uniqlo Hoodie 7', 'Adidas Jacket 171', 'Puma Jacket 266',
       'H&M Shoes 73', 'Puma Dress 46', 'Uniqlo Jacket 56',
       'Adidas Shoes 170', 'Nike Jeans 178', 'Uniqlo Jacket 239',
       'Adidas Jacket 34', 'Puma Shoes 21', 'Puma Jeans 1',
       'Zara Jeans 288', 'Nike Jacket 139', 'Zara Jacket 284',
       'Zara T-Shirt 44', "Levi's Jacket 227", "Levi's Jeans 216",
       'Zara T-Shirt 155', 'Uniqlo Jeans 290', "Levi's Jeans 4",
       'Nike Jeans 55', 'Puma Jeans 74', 'Zara Jeans 80',
       "Levi's Shoes 50", 'H&M Jacket 201', 'H&M Jacket 121',
       'Uniqlo Dress 225', "Levi's Jacket 88", 'Uniqlo T-Shirt 253',
       "Levi's Jacket 218", 'Adidas Hoodie 235', 'H&M Hoodie 228',
       'Nike T-Shirt 72', 'Nike Dress 269', 'Adidas Jacket 90',
       'H&M Jacket 289', 'Zara Dress 193', 'H&M Shoes 93',
       'Nike Jeans 260', 'Uniqlo Jeans 298', 'Uniqlo Jeans 129',
       'H&M Jacket 231', 'Uniqlo T-Shirt 294', 'Uniqlo Dress 130',
       'Nike Hoodie 147', 'Uniqlo T-Shirt 99', 'Adidas Shoes 209',
       "Levi's Dress 37", "Levi's Shoes 107", 'Nike Jacket 287',
       'H&M T-Shirt 219', "Levi's Hoodie 265", 'H&M Shoes 277',
       'Uniqlo Dress 280', 'Zara Jacket 242', 'Zara Shoes 32',
       'Puma Hoodie 19', 'Nike T-Shirt 214', 'Zara Dress 42',
       'Nike Dress 10', 'Zara Jeans 199', 'Nike Dress 189',
       'Uniqlo Jeans 212', 'H&M Dress 30', 'H&M Hoodie 204',
       "Levi's Hoodie 40", 'Uniqlo Jacket 183', 'Uniqlo T-Shirt 249',
       'Adidas Shoes 23', 'H&M Jacket 173', 'Uniqlo Jeans 196',
       'Puma Jeans 141', 'Puma Jacket 186', "Levi's Hoodie 20",
       'Puma Jeans 133', 'Puma Hoodie 293', 'H&M Jacket 145',
       'Adidas Dress 185', 'Puma Hoodie 77', 'Puma Shoes 215',
       'H&M T-Shirt 138', 'Puma T-Shirt 60', 'Adidas Jeans 118',
       "Levi's Hoodie 292", 'Zara T-Shirt 86', 'Nike Shoes 182',
       'Zara Jeans 94', 'H&M Dress 261', 'Uniqlo Shoes 175',
       'Adidas Shoes 119', 'Zara Shoes 100', 'Puma Hoodie 57',
       'Puma Jeans 62', 'H&M Jacket 81', 'Puma Shoes 267',
       'Puma Dress 286', 'Adidas Jeans 150', 'Adidas T-Shirt 247',
       "Levi's Shoes 58", 'Adidas T-Shirt 229', 'Nike Shoes 11',
       'Nike Dress 275', 'Adidas T-Shirt 12', 'Puma Jeans 104',
       "Levi's Jeans 190", "Levi's Dress 120", 'Puma T-Shirt 78',
       'Adidas Jacket 54', 'Adidas Shoes 281', 'Zara Jeans 152',
       'Zara Hoodie 191', 'Uniqlo Dress 241', 'Puma Jacket 97',
       'Adidas Dress 53', 'Adidas Dress 61', 'H&M T-Shirt 194',
       'Zara Jacket 110', "Levi's Jeans 49", 'Zara Dress 188',
       'Uniqlo Shoes 257', 'Adidas Hoodie 45', 'Puma Hoodie 162',
       'Adidas T-Shirt 268', 'Nike Dress 240', 'Puma Hoodie 244',
       'Puma Jacket 206', 'Adidas Hoodie 154', 'Puma Hoodie 85',
       'Nike Shoes 177', 'Uniqlo Shoes 69', 'Adidas Dress 251',
       'Nike T-Shirt 174', 'Zara Jeans 41', "Levi's T-Shirt 264",
       'Uniqlo Hoodie 137', "Levi's Shoes 236", 'Adidas T-Shirt 273',
       'Adidas Jeans 200', 'H&M Hoodie 157', 'Zara Shoes 151',
       'Adidas T-Shirt 159', 'Puma Hoodie 156', 'Nike Jeans 132',
       'Puma Hoodie 176', 'Zara Hoodie 259', 'Nike Hoodie 35',
       'Adidas Shoes 262', 'Uniqlo Hoodie 116', 'Nike T-Shirt 153',
       'Puma Hoodie 291', "Levi's Jacket 87", 'H&M Jacket 230',
       'Uniqlo Jacket 252', 'Puma T-Shirt 22', 'H&M Jacket 246',
       'Adidas Jeans 167', "Levi's Shoes 299", "Levi's T-Shirt 47",
       'Adidas Jeans 112', "Levi's Jeans 31", 'Puma Shoes 122',
       'Zara Hoodie 2', "Levi's T-Shirt 29", 'Zara Shoes 70'],
      dtype=object)

In [30]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [31]:
df.columns

Index(['order_id', 'customer_id', 'age', 'gender', 'country', 'city',
       'registration_date', 'product_id', 'product_name', 'brand', 'category',
       'condition', 'price', 'order_date', 'quantity', 'total_price'],
      dtype='object')

In [32]:
#create a column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels=labels)

In [33]:
df[['age','age_group']].head(10)

    age    age_group
0  59.0       Senior
1  61.0       Senior
2  37.0        Adult
3  49.0  Middle-aged
4  36.0        Adult
5  44.0  Middle-aged
6  23.0  Young Adult
7  39.0        Adult
8  41.0        Adult
9  32.0        Adult

In [34]:
df["product_type"] = df["product_name"].apply(
    lambda x: " ".join(str(x).split()[1:-1])
)

In [35]:
df["product_type"]

0        Jacket
1       T-Shirt
2         Jeans
3       T-Shirt
4         Jeans
         ...
9995     Hoodie
9996      Shoes
9997      Jeans
9998      Shoes
9999     Jacket
Name: product_type, Length: 10000, dtype: object

In [36]:
df["brand"] = df["product_name"].apply(
    lambda x: " ".join(str(x).split()[0])
)

In [37]:
df.head(5)

,order_id,customer_id,age,gender,country,city,registration_date,product_id,product_name,brand,category,condition,price,order_date,quantity,total_price,age_group,product_type
0,1,443,59.0,Female,Latvia,Daugavpils,2025-01-06,179,Levi's Jacket 179,L e v i ' s,Jacket,Like New,49.57,2024-12-14,1,49.57,Senior,Jacket
1,2,1991,61.0,Female,Latvia,Daugavpils,2024-02-03,296,Nike T-Shirt 296,N i k e,T-Shirt,Fair,43.11,2025-06-16,1,43.11,Senior,T-Shirt
2,3,1667,37.0,Male,Poland,Krakow,2024-04-07,187,Nike Jeans 187,N i k e,Jeans,New,143.69,2025-04-07,1,143.69,Adult,Jeans
3,4,1837,49.0,Female,Poland,Krakow,2024-06-11,158,Nike T-Shirt 158,N i k e,T-Shirt,New,124.47,2024-10-07,3,373.41,Middle-aged,T-Shirt
4,5,1433,36.0,Male,Estonia,Tartu,2025-12-02,256,Nike Jeans 256,N i k e,Jeans,Good,84.33,2025-09-11,3,252.99,Adult,Jeans

In [40]:
df.to_csv("dataset.csv",index=False)